# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: app/proto/Orders.proto for package 'rpc'

require 'grpc'
require 'app/proto/Orders_pb'

module Rpc
  module Orders
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rpc.Orders'

      # Demonstrates a request response call
      rpc :GetOrder, ::Rpc::GetOrderReq, ::Rpc::GetOrderResp
      # Demonstrates a server streamer call
      rpc :GetOrders, ::Rpc::GetOrdersReq, stream(::Rpc::Order)
      # Demonstrates a client streaming call
      rpc :CreateOrders, stream(::Rpc::Order), ::Rpc::CreateOrdersResp
      # Demonstrates a bidirectional streaming call
      rpc :CreateOrdersInStream, stream(::Rpc::Order), stream(::Rpc::Order)
    end

    Stub = Service.rpc_stub_class
  end
end
