# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proto/Orders.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("app/proto/Orders.proto", :syntax => :proto3) do
    add_message "rpc.Order" do
      optional :id, :uint32, 1
      optional :number, :string, 2
      optional :total, :float, 3
    end
    add_message "rpc.GetOrderReq" do
      optional :id, :uint32, 1
    end
    add_message "rpc.GetOrderResp" do
      optional :order, :message, 1, "rpc.Order"
    end
    add_message "rpc.GetOrdersReq" do
      optional :search, :string, 1
      optional :limit, :uint32, 2
    end
    add_message "rpc.CreateOrdersResp" do
      repeated :orders, :message, 1, "rpc.Order"
    end
  end
end

module Rpc
  Order = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.Order").msgclass
  GetOrderReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetOrderReq").msgclass
  GetOrderResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetOrderResp").msgclass
  GetOrdersReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetOrdersReq").msgclass
  CreateOrdersResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.CreateOrdersResp").msgclass
end
